vich_uploader:
    db_driver: orm
    metadata:
        type: attribute


    mappings:
        user_image:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
